name: Validate Feature Branch Name

on:
  pull_request:
    branches:
      - 'feature/**'

jobs:
  validate-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Validate Feature Branch Name
        run: |
          BRANCH_NAME="${{ github.head_ref }}"

          echo "Validando branch: $BRANCH_NAME"

          if [[ ! "$BRANCH_NAME" =~ ^(feat|fix|docs|refactor|test|chore)\/HU-[0-9]+\/[0-9]+\/[a-z0-9-]+$ ]]; then
            echo "Nome de branch inválido!"
            echo ""
            echo "Padrão esperado:"
            echo "feat/HU-21/09/cadastro-usuario"
            echo "fix/HU-35/20/correcao-login"
            echo "doc/HU-40/56/atualizacao-wiki"
            exit 1
          fi

          echo "Nome de branch válido!"